---
# Source: ingressmonitorcontroller/templates/imc.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: ingressmonitorcontroller
    version: 1.0.29
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.29"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://api.uptimerobot.com/v2/
      username: null
      password: null
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
---
# Source: ingressmonitorcontroller/templates/imc.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    version: 1.0.29
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.29"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
---
# Source: ingressmonitorcontroller/templates/imc.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressmonitorcontroller-role
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - ingresses
  verbs:
  - list
  - get
  - update
  - patch
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - list
  - get
  - watch
---
# Source: ingressmonitorcontroller/templates/imc.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingressmonitorcontroller-role-binding
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: default
---
# Source: ingressmonitorcontroller/templates/imc.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingressmonitorcontroller
  labels:
    app: ingressmonitorcontroller
    version: 1.0.29
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.29"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingressmonitorcontroller
      labels:
        app: ingressmonitorcontroller
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:1.0.29"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume
