apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: uptimerobot-config-example
spec:
  monitorName: "custom-overwrite-name-P2"
  forceHttps: true
  providers: "UptimeRobot"
  healthEndpoint: "/healthzzz"
  urlFrom:
    routeRef:
      name: frontend
  uptimeRobotConfig:
    interval: 600
    monitorType: "http"
    KeywordExists: "yes"
    KeywordValue: "404"
