// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppInsightsConfig) DeepCopyInto(out *AppInsightsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppInsightsConfig.
func (in *AppInsightsConfig) DeepCopy() *AppInsightsConfig {
	if in == nil {
		return nil
	}
	out := new(AppInsightsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMonitor) DeepCopyInto(out *EndpointMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMonitor.
func (in *EndpointMonitor) DeepCopy() *EndpointMonitor {
	if in == nil {
		return nil
	}
	out := new(EndpointMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMonitorList) DeepCopyInto(out *EndpointMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMonitorList.
func (in *EndpointMonitorList) DeepCopy() *EndpointMonitorList {
	if in == nil {
		return nil
	}
	out := new(EndpointMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMonitorSpec) DeepCopyInto(out *EndpointMonitorSpec) {
	*out = *in
	if in.URLFrom != nil {
		in, out := &in.URLFrom, &out.URLFrom
		*out = new(URLSource)
		(*in).DeepCopyInto(*out)
	}
	if in.UptimeRobotConfig != nil {
		in, out := &in.UptimeRobotConfig, &out.UptimeRobotConfig
		*out = new(UptimeRobotConfig)
		**out = **in
	}
	if in.UptimeConfig != nil {
		in, out := &in.UptimeConfig, &out.UptimeConfig
		*out = new(UptimeConfig)
		**out = **in
	}
	if in.UpdownConfig != nil {
		in, out := &in.UpdownConfig, &out.UpdownConfig
		*out = new(UpdownConfig)
		**out = **in
	}
	if in.StatusCakeConfig != nil {
		in, out := &in.StatusCakeConfig, &out.StatusCakeConfig
		*out = new(StatusCakeConfig)
		**out = **in
	}
	if in.PingdomConfig != nil {
		in, out := &in.PingdomConfig, &out.PingdomConfig
		*out = new(PingdomConfig)
		**out = **in
	}
	if in.AppInsightsConfig != nil {
		in, out := &in.AppInsightsConfig, &out.AppInsightsConfig
		*out = new(AppInsightsConfig)
		**out = **in
	}
	if in.GCloudConfig != nil {
		in, out := &in.GCloudConfig, &out.GCloudConfig
		*out = new(GCloudConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMonitorSpec.
func (in *EndpointMonitorSpec) DeepCopy() *EndpointMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMonitorStatus) DeepCopyInto(out *EndpointMonitorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMonitorStatus.
func (in *EndpointMonitorStatus) DeepCopy() *EndpointMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCloudConfig) DeepCopyInto(out *GCloudConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCloudConfig.
func (in *GCloudConfig) DeepCopy() *GCloudConfig {
	if in == nil {
		return nil
	}
	out := new(GCloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressURLSource) DeepCopyInto(out *IngressURLSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressURLSource.
func (in *IngressURLSource) DeepCopy() *IngressURLSource {
	if in == nil {
		return nil
	}
	out := new(IngressURLSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingdomConfig) DeepCopyInto(out *PingdomConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingdomConfig.
func (in *PingdomConfig) DeepCopy() *PingdomConfig {
	if in == nil {
		return nil
	}
	out := new(PingdomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteURLSource) DeepCopyInto(out *RouteURLSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteURLSource.
func (in *RouteURLSource) DeepCopy() *RouteURLSource {
	if in == nil {
		return nil
	}
	out := new(RouteURLSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCakeConfig) DeepCopyInto(out *StatusCakeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCakeConfig.
func (in *StatusCakeConfig) DeepCopy() *StatusCakeConfig {
	if in == nil {
		return nil
	}
	out := new(StatusCakeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLSource) DeepCopyInto(out *URLSource) {
	*out = *in
	if in.IngressRef != nil {
		in, out := &in.IngressRef, &out.IngressRef
		*out = new(IngressURLSource)
		**out = **in
	}
	if in.RouteRef != nil {
		in, out := &in.RouteRef, &out.RouteRef
		*out = new(RouteURLSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLSource.
func (in *URLSource) DeepCopy() *URLSource {
	if in == nil {
		return nil
	}
	out := new(URLSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdownConfig) DeepCopyInto(out *UpdownConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdownConfig.
func (in *UpdownConfig) DeepCopy() *UpdownConfig {
	if in == nil {
		return nil
	}
	out := new(UpdownConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeConfig) DeepCopyInto(out *UptimeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeConfig.
func (in *UptimeConfig) DeepCopy() *UptimeConfig {
	if in == nil {
		return nil
	}
	out := new(UptimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeRobotConfig) DeepCopyInto(out *UptimeRobotConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeRobotConfig.
func (in *UptimeRobotConfig) DeepCopy() *UptimeRobotConfig {
	if in == nil {
		return nil
	}
	out := new(UptimeRobotConfig)
	in.DeepCopyInto(out)
	return out
}
