{{- if .Values.rbac.create -}}
{{- if  eq .Values.watchNamespaces "" }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-monitor-controller.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-monitor-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-monitor-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}

---
{{- if .Values.rbac.allowProxyRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-monitor-controller.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-monitor-controller.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-monitor-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}

---
{{- if .Values.rbac.allowMetricsReaderRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-monitor-controller.fullname" . }}-metrics-reader-rolebbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-monitor-controller.fullname" . }}-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-monitor-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}

{{- end }}
