
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-monitor-controller.fullname" . }}-metrics-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "ingress-monitor-controller.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "ingress-monitor-controller.selectorLabels" . | nindent 4 }}
