{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name | default .Release.Name }}
  namespace: {{ include "ingress-monitor-controller.namespace" . }}
  labels:
    app.kubernetes.io/name: '{{ include "ingress-monitor-controller.name" . }}'
    app.kubernetes.io/instance: '{{ .Values.name | default .Release.Name }}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "ingress-monitor-controller.name" . }}'
      app.kubernetes.io/instance: '{{ .Values.name | default .Release.Name }}'
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ not .Values.certManager.enabled }}
        {{- if .Values.certManager.enabled }}
        serverName: {{ include "ingress-monitor-controller.fullname" . }}-metrics-service.{{ include "ingress-monitor-controller.namespace" . }}.svc
        {{- if .Values.certManager.injectCA }}
        ca:
          secret:
            name: {{ include "ingress-monitor-controller.fullname" . }}-metrics-tls
            key: ca.crt
        {{- end }}
        {{- end }}
  namespaceSelector:
    matchNames:
    - '{{ include "ingress-monitor-controller.namespace" . }}'
{{- end }}
